name: Frontend run code coverage and build docs

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd src/frontend
        npm install

    - name: Run eslint check
      run: |
        cd src/frontend/src
        npx eslint ./**/*.js

    - name: Run the frontend tests
      run: |
        cd src/frontend
        npm test -- --coverage --updateSnapshot

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Build jsdoc documentation
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./src/frontend/src
        output_dir: ./docs/frontendDocs/left-overs/0.1.0
        recurse: true
        front_page: README.md

    - name: Upload jsdoc documentation to github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./docs/frontendDocs
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: frontendDocs
